# File generated by Flopy version 3.3.5 on 12/09/2021 at 09:36:05.
BEGIN ATTRIBUTES
  NAMES  rch_lu1
  METHOD  linearend
END ATTRIBUTES

BEGIN TIMESERIES
    OPEN/CLOSE  'rch.ts_timeseries.txt'
END TIMESERIES

