# File generated by Flopy version 3.3.5 on 12/03/2021 at 16:59:58.
BEGIN ATTRIBUTES
  NAMES  rch_lu1
  METHOD  linearend
END ATTRIBUTES

BEGIN TIMESERIES
    OPEN/CLOSE  'rch.ts_timeseries.txt'
END TIMESERIES

